version: '3.8'
services:
    pfcp-kitchen-sink:
        container_name: "pfcp-kitchen-sink"
        image: tariromukute/pfcp-kitchen-sink:latest
        volumes:
            - ./sessions-oai-upf-vpp.yaml:/app/sessions.yaml
        command: ./pfcpclient -r 192.168.70.134:8805 -s sessions.yaml
        depends_on:
            - vpp-upf
        networks:
            public_net:
                ipv4_address: 192.168.70.131
    tc-gtpu-tnl:
        container_name: "tc-gtpu-tnl"
        image: tariromukute/tc-gtpu:latest
        command: tail -f /dev/null
        volumes:
            - /sys/kernel/debug/:/sys/kernel/debug/
            - /Users/tariromukute/Documents/phd/tc-gtpu:/home
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        # cap_drop:
        #     - ALL
        depends_on:
            - vpp-upf
            - pfcp-kitchen-sink
        networks:
            public_net:
                ipv4_address: 192.168.70.130
    vpp-upf:
        privileged: true
        container_name: "vpp-upf"
        image: oaisoftwarealliance/oai-upf-vpp:develop
        environment:
            - IF_1_IP=192.168.70.201
            - IF_1_TYPE=N4
            - IF_2_IP=192.168.72.201
            - IF_2_TYPE=N3
            - IF_2_NWI=access.oai.org
            - IF_2_DNAI=access
            - IF_3_IP=192.168.73.201
            - IF_3_TYPE=N6
            - IF_3_IP_REMOTE=192.168.73.135 # EXT-DN IP Address
            - IF_3_NWI=internet.oai.org.pri
            - IF_3_DNAI=internet-primary
            - IF_4_IP=192.168.74.201
            - IF_4_TYPE=N6
            - IF_4_IP_REMOTE=192.168.74.135 # EXT-DN IP Address
            - IF_4_NWI=internet.oai.org.sec
            - IF_4_DNAI=internet-secondary
            - NAME=VPP-UPF
            - MNC=95
            - MCC=208
            - REALM=3gppnetwork.org
            - VPP_MAIN_CORE=0
            - VPP_CORE_WORKER=1
#           - VPP_PLUGIN_PATH=/usr/lib64/vpp_plugins/                # RHEL7
            - VPP_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vpp_plugins/ # Ubntu18.04
            - SNSSAI_SD=123
            - SNSSAI_SST=222
            - DNN=default
            - REGISTER_NRF=no
            #changes for HTTP2
            - NRF_PORT=8080
            - HTTP_VERSION=2
        healthcheck:
            test: /bin/bash -c "pgrep vpp"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.70.134
            public_net_access:
                ipv4_address: 192.168.72.134
            public_net_core_pri:
                ipv4_address: 192.168.73.134
            public_net_core_sec:
                ipv4_address: 192.168.74.134
    oai-ext-dn:
        privileged: true
        init: true
        container_name: "oai-ext-dn"
        image: oaisoftwarealliance/trf-gen-cn5g:latest
        entrypoint: /bin/bash -c \
              "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 12.1.1.2/32 via 192.168.73.201 dev eth0;"\
              "ip route add 12.1.1.3/32 via 192.168.74.201 dev eth1; ip route; sleep infinity"
        command: ["/bin/bash", "-c", "trap : SIGTERM SIGINT; sleep infinity & wait"]
        healthcheck:
            test: /bin/bash -c "iptables -L -t nat | grep MASQUERADE"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net_core_pri:
                ipv4_address: 192.168.73.135
            public_net_core_sec:
                ipv4_address: 192.168.74.135
networks:
    public_net:
        driver: bridge
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: 192.168.70.0/24
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
    public_net_access:
        name: oai-public-access
        ipam:
            config:
                - subnet: 192.168.72.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-access"
    public_net_core_pri:
        name: oai-public-core-pri
        ipam:
            config:
                - subnet: 192.168.73.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-core-pri"
    public_net_core_sec:
        name: oai-public-core-sec
        ipam:
            config:
                - subnet: 192.168.74.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-core-sec"